<%@include file="WEB-INF/fragmentos/top.jspf"%>

		<div class="container"> 
			<div class="table-responsive"> 
				<table class="table table-bordered table-hover"> 
					<tr class="active info"> 
						<th>Codigox</th> 
						<th>Nombre</th> 
						<th>Producto</th> 
						<th>Cantidad</th> 
						<th>Fecha</th> 
						<th>Precio Total</th> 

					</tr> 
					<tr> 
						<td>001</td> 
						<td>Jorge</td> 
						<td>Gravol</td> 
						<td>2</td> 
						<td>07/09/2015</td> 
						<td>3.00</td> 
					</tr> 
					<tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr> 
					<tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr> 
					<tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>
                                        <tr> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
						<td></td> 
					</tr>

				</table> 
			</div> 

		</div> 
		<script type="text/javascript" 
        	src="jquery/jquery-2.1.4.min.js" 
        	></script>
        <script type="text/javascript" 
        	src="bootstrap/js/bootstrap.min.javascript" 
        	></script>
    </body>
</html>